#!/bin/bash

# A script to send a sample log to the log ingestion API.
# Usage: ./scripts/test_log_ingestion.sh <PROJECT_ID> <API_KEY>

set -e

PROJECT_ID=$1
API_KEY=$2

if [ -z "$PROJECT_ID" ] || [ -z "$API_KEY" ]; then
    echo "Usage: $0 <PROJECT_ID> <API_KEY>"
    echo ""
    echo "Please provide the Project ID and the API Key for the project."
    echo "You can get these values from the web interface at http://localhost:8084 after creating a project."
    exit 1
fi

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
EVENT_NAME="test_event_from_script"
USER_ID="user-$(shuf -i 1000-9999 -n 1)"
REQUEST_ID=$(cat /proc/sys/kernel/random/uuid)

echo "Sending a sample log with the following details:"
echo "Project ID: $PROJECT_ID"
echo "API Key: [REDACTED]"
echo "Timestamp: $TIMESTAMP"
echo "Event Name: $EVENT_NAME"
echo "------------------------------------"

# Construct the JSON payload
JSON_PAYLOAD=$(cat <<EOF
{
  "name": "$EVENT_NAME",
  "timestamp": "$TIMESTAMP",
  "searchable_keys": {
    "folan1": "$USER_ID",
    "folan2": "$REQUEST_ID"
  },
  "full_payload": {
    "ip_address": "127.0.0.1",
    "user_agent": "test-script/1.0",
    "details": "This is a test log generated by the test_log_ingestion.sh script.",
    "random_number": "$(shuf -i 1-100 -n 1)"
  }
}
EOF
)

# Send the request using curl
curl -i -X POST "http://localhost:8083/api/projects/${PROJECT_ID}/logs" \
-H "Content-Type: application/json" \
-H "X-API-KEY: ${API_KEY}" \
-d "$JSON_PAYLOAD"

echo ""
echo "------------------------------------"
echo "Log ingestion request sent."
echo "Check the logs of the 'log-processor' service to see if it was processed successfully:"
echo "docker-compose logs -f log-processor"
